# Project Definition
project:
  name: n8n-nodes-cloudblue-simpleapi
  description: An n8n community node for CloudBlue Connect SimpleAPI that provides a simple interface to interact with CloudBlue Connect services via n8n
  version: "1.0"  # Semantic versioning
  objective: Create an n8n node for interacting with CloudBlue Connect SimpleAPI
  quality_requirements:
    - requirement: API Specification Compliance
      validation: Validate against SimpleAPI (1.15).yaml specification
    - requirement: Code Quality
      validation: ESLint and TypeScript type checking
    - requirement: Test Coverage
      validation: Unit tests for core functionality
  success_criteria:
    business: Successfully integrate with CloudBlue Connect services via n8n
    technical: Complete implementation of all API endpoints with proper error handling
  dependencies:
    required:
      - name: n8n-workflow
        version: "^1.0.0"
      - name: n8n-core
        version: "^1.0.0"
      - name: axios
        version: "^1.0.0"
    development:
      - name: typescript
        version: "^4.0.0"
      - name: eslint
        version: "^8.0.0"
      - name: jest
        version: "^29.0.0"
  configuration:
    linting:
      - eslint
      - prettier
    testing:
      framework: jest
      coverage:
        statements: 80
        branches: 80
        functions: 80
        lines: 80
